service: notifications-service

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  iam:
    role:
      statements:
        - ${file(iam/SendMailIAM.yml):SendMailIAM}
  environment:
    VERIFIED_SENDER: ${self:custom.verified_ses_email}

resources:
  Resources:
    MailQueueRes: ${file(resources/MailQueueRes.yml):MailQueue}
  Outputs:
    MailQueueArn: ${file(resources/MailQueueRes.yml):Outputs.MailQueueArn}
    MailQueueUrl: ${file(resources/MailQueueRes.yml):Outputs.MailQueueUrl}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - sqs:
          arn: ${self:custom.MailQueue.arn}
          batchSize: 1 # default is 10

custom:
  MailQueue:
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueueRes.Arn
    url: !Ref MailQueueRes # get the queue url
  verified_ses_email: salouri@gmail.com
  bundle:
    linting: false
