service: notifications-service

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  iam:
    role:
      statements:
        - ${file(iam/SendMailIAM.yml):SendMailIAM}
  environment:
    # AWS_REGION: ${self:provider.region}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    # events:
    #   - http:
    #       method: GET
    #       path: /sendMail

custom:
  bundle:
    linting: false
